export interface ImageObject {
  url: string
  width: number
  height: number
}

export interface VideoThumbnail extends ImageObject {
  quality: string
}

export interface Video {
  type: string
  title: string
  videoId: string
  author: string
  authorId: string
  authorUrl: string
  authorVerified: boolean
  authorThumbnails?: ImageObject[]
  videoThumbnails: VideoThumbnail[]
  description: string
  descriptionHtml: string
  viewCount: number
  viewCountText: string
  published: number
  publishedText: string
  lengthSeconds: number
  liveNow: boolean
  premium: boolean
  hasCaptions: boolean
  isUpcoming: boolean
  isNew: boolean
  is3d: boolean
  is4k: boolean
  is8k: boolean
  isVr180: boolean
  isVr360: boolean
}

export interface SearchVideoShape extends Video {
  type: 'video'
  premiereTimestamp?: number
}

export interface SearchChannelShape {
  type: 'channel'
  author: string
  authorId: string
  authorUrl: string
  authorVerified: boolean
  authorThumbnails: ImageObject[]
  autoGenerated: boolean
  subCount: number
  videoCount: number
  channelHandle: string | null
  description: string
  descriptionHtml: string
}

export interface SearchPlaylistShape {
  type: 'playlist'
  title: string
  playlistId: string
  playlistThumbnail: string | null
  author: string
  authorId: string
  authorUrl: string
  authorVerified: boolean
  videoCount: number
  videos: {
    title: string
    videoId: string
    lengthSeconds: number
    videoThumbnails: VideoThumbnail[]
  }[]
}

export interface SearchHashtagShape {
  type: 'hashtag'
  title: string
  url: string
  videoCount: number
  channelCount: number
}

export type SearchItemShape =
  | SearchVideoShape
  | SearchChannelShape
  | SearchPlaylistShape
  | SearchHashtagShape
  | { type: 'category'; title: string; contents: SearchItemShape[] }
  | { type: 'parse-error'; errorMessage: string | null; errorBacktrace: string | null }

export type GridItem =
  | { kind: 'video'; video: SearchVideoShape; thumbnailSrc?: string; avatarSrc?: string }
  | { kind: 'channel'; channel: SearchChannelShape; avatarSrc?: string }
  | { kind: 'playlist'; playlist: SearchPlaylistShape; thumbnailSrc?: string }
  | { kind: 'hashtag'; hashtag: SearchHashtagShape }
  | { kind: 'parse-error'; message: string | null }

export interface RelatedVideo {
  title: string
  videoId: string
  author: string
  authorId: string
  authorUrl: string
  authorVerified: boolean
  videoThumbnails: VideoThumbnail[]
  lengthSeconds: number
  published: number
  publishedText: string
  viewCountText: string
}

export interface VideoDetail extends Video {
  formatStreams: unknown[]
  adaptiveFormats: unknown[]
  captions: unknown[]
  dashUrl: string | null
  hlsUrl: string | null
  storyboards: unknown[]
  recommendedVideos: RelatedVideo[]
  likeCount: number
  dislikeCount: number
  subCountText: string
  rating: number
  allowedRegions: string[]
  genre: string
  genreUrl: string | null
  isFamilyFriendly: boolean
  isListed: boolean
  isPostLiveDvr: boolean
  keywords: string[]
  premiereTimestamp?: number
  paid: boolean
}

export interface ApiComment {
  author: string
  authorId: string
  authorIsChannelOwner: boolean
  authorThumbnail: string
  authorUrl: string
  commentId: string
  content: string
  contentHtml: string
  isEdited: boolean
  isPinned: boolean
  isSponsor: boolean
  likeCount: number
  published: number
  publishedText: string
  verified: boolean
}

export interface CommentsResponse {
  commentCount?: number
  comments: ApiComment[]
  videoId?: string
}

export interface ChannelDetail {
  author: string
  authorId: string
  authorUrl: string
  authorVerified: boolean
  authorThumbnails: ImageObject[]
  authorBanners: ImageObject[]
  subCount: number
  totalViews: number
  joined: number
  tabs: string[]
  latestVideos: Video[]
  description: string
  descriptionHtml: string
  pronouns: string[] | null
  relatedChannels: unknown[]
  tags: unknown[]
  autoGenerated: boolean
  isFamilyFriendly: boolean
  allowedRegions: string[]
  ageGated: boolean
}

export interface ChannelVideosResponse {
  videos: Video[]
  continuation?: string | null
}

export interface CommunityPost {
  author: string
  authorId: string
  authorIsChannelOwner: boolean
  authorThumbnails: ImageObject[]
  authorUrl: string
  commentId: string
  content: string
  contentHtml: string
  isEdited: boolean
  likeCount: number
  published: number
  publishedText: string
  replyCount: number
  attachment: unknown
}

export interface CommunityResponse {
  authorId: string
  comments: CommunityPost[]
}

export interface PlaylistVideo {
  author: string
  authorId: string
  authorUrl: string
  index: number
  lengthSeconds: number
  liveNow: boolean
  title: string
  type: string
  videoId: string
  videoThumbnails: VideoThumbnail[]
}

export interface PlaylistDetail {
  author: string
  authorId: string
  authorThumbnails: ImageObject[]
  authorUrl: string
  description: string
  descriptionHtml: string
  isListed: boolean
  playlistId: string
  playlistThumbnail: string
  subtitle: string | null
  title: string
  type: string
  updated: number
  videoCount: number
  videos: PlaylistVideo[]
  viewCount: number
}
