export interface ImageObject {
  url: string
  width: number
  height: number
}

export interface VideoThumbnail extends ImageObject {
  quality: string
}

export interface Video {
  type: string
  title: string
  videoId: string
  author: string
  authorId: string
  authorUrl: string
  authorVerified: boolean
  authorThumbnails: ImageObject[]
  videoThumbnails: VideoThumbnail[]
  description: string
  descriptionHtml: string
  viewCount: number
  viewCountText: string
  published: number
  publishedText: string
  lengthSeconds: number
  liveNow: boolean
  premium: boolean
  hasCaptions: boolean
  isUpcoming: boolean
  isNew: boolean
  is3d: boolean
  is4k: boolean
  is8k: boolean
  isVr180: boolean
  isVr360: boolean
}

export interface SearchVideoShape extends Video {
  type: 'video'
  premiereTimestamp?: number
}

export interface SearchChannelShape {
  type: 'channel'
  author: string
  authorId: string
  authorUrl: string
  authorVerified: boolean
  authorThumbnails: ImageObject[]
  autoGenerated: boolean
  subCount: number
  videoCount: number
  channelHandle: string | null
  description: string
  descriptionHtml: string
}

export interface SearchPlaylistShape {
  type: 'playlist'
  title: string
  playlistId: string
  playlistThumbnail: string | null
  author: string
  authorId: string
  authorUrl: string
  authorVerified: boolean
  videoCount: number
  videos: {
    title: string
    videoId: string
    lengthSeconds: number
    videoThumbnails: VideoThumbnail[]
  }[]
}

export interface SearchHashtagShape {
  type: 'hashtag'
  title: string
  url: string
  videoCount: number
  channelCount: number
}

export type SearchItemShape =
  | SearchVideoShape
  | SearchChannelShape
  | SearchPlaylistShape
  | SearchHashtagShape
  | { type: 'category'; title: string; contents: SearchItemShape[] }
  | { type: 'parse-error'; errorMessage: string | null; errorBacktrace: string | null }

export type GridItem =
  | { kind: 'video'; video: SearchVideoShape; thumbnailSrc?: string }
  | { kind: 'channel'; channel: SearchChannelShape; avatarSrc?: string }
  | { kind: 'playlist'; playlist: SearchPlaylistShape; thumbnailSrc?: string }
  | { kind: 'hashtag'; hashtag: SearchHashtagShape }
  | { kind: 'parse-error'; message: string | null }
