import type {
  ApiComment,
  CommunityPost,
  GridItem,
  PlaylistVideo,
  RelatedVideo,
  SearchChannelShape,
  SearchHashtagShape,
  SearchPlaylistShape,
  SearchVideoShape,
} from '../lib/api-types'

const DAY = 86_400
const now = Math.floor(Date.now() / 1000)

export const sampleVideo: SearchVideoShape = {
  type: 'video',
  title: 'The Shape of Stories — Kurt Vonnegut',
  videoId: 'GOGru_4z1Vc',
  author: 'Evan Esar',
  authorId: 'UCQw3ljbuT9jRGd',
  authorUrl: '/channel/UCQw3ljbuT9jRGd',
  authorVerified: true,
  authorThumbnails: [],
  videoThumbnails: [
    { quality: 'medium', url: '/vi/GOGru_4z1Vc/mqdefault.jpg', width: 320, height: 180 },
  ],
  description: '',
  descriptionHtml: '',
  viewCount: 1_234_567,
  viewCountText: '1,234,567 views',
  published: now - 3 * DAY,
  publishedText: '3 days ago',
  lengthSeconds: 134,
  liveNow: false,
  premium: false,
  hasCaptions: true,
  isUpcoming: false,
  isNew: false,
  is3d: false,
  is4k: false,
  is8k: false,
  isVr180: false,
  isVr360: false,
}

export const liveVideo: SearchVideoShape = {
  ...sampleVideo,
  videoId: 'liveStream123',
  title: 'Live: Testing the new Invidious interface',
  lengthSeconds: 0,
  liveNow: true,
  viewCount: 25_000,
  published: now - 3600,
}

export const upcomingVideo: SearchVideoShape = {
  ...sampleVideo,
  videoId: 'premiere123',
  title: 'Premiere: Invidious 2.0 announcement',
  isUpcoming: true,
  isNew: true,
  liveNow: false,
  published: now + 2 * DAY,
  viewCount: 0,
}

export const sampleChannel: SearchChannelShape = {
  type: 'channel',
  author: 'Invidious',
  authorId: 'UC4QobU6STFB0P71PMvOGN5A',
  authorUrl: '/channel/UC4QobU6STFB0P71PMvOGN5A',
  authorVerified: true,
  authorThumbnails: [{ url: '/ggpht/avatar.jpg', width: 176, height: 176 }],
  autoGenerated: false,
  subCount: 45_600,
  videoCount: 320,
  channelHandle: '@invidious',
  description: 'An open source alternative front-end to YouTube.',
  descriptionHtml: '<p>An open source alternative front-end to YouTube.</p>',
}

export const samplePlaylist: SearchPlaylistShape = {
  type: 'playlist',
  title: 'Music for focused work',
  playlistId: 'PLyK5TvpsSRzBcT6u1iLDf',
  playlistThumbnail: '/vi/GOGru_4z1Vc/mqdefault.jpg',
  author: 'Focus Sounds',
  authorId: 'UCfocus123',
  authorUrl: '/channel/UCfocus123',
  authorVerified: false,
  videoCount: 42,
  videos: [],
}

export const sampleHashtag: SearchHashtagShape = {
  type: 'hashtag',
  title: '#opensource',
  url: '/hashtag/opensource',
  videoCount: 890_000,
  channelCount: 12_000,
}

export const mixedGrid: GridItem[] = [
  {
    kind: 'video',
    video: sampleVideo,
    thumbnailSrc: 'https://placehold.co/320x180/232323/f0f0f0?text=Thumbnail',
    avatarSrc: 'https://placehold.co/48x48/232323/f0f0f0?text=Avatar',
  },
  {
    kind: 'video',
    video: liveVideo,
    thumbnailSrc: 'https://placehold.co/320x180/232323/f0f0f0?text=Live',
    avatarSrc: 'https://placehold.co/48x48/232323/f0f0f0?text=Avatar',
  },
  {
    kind: 'channel',
    channel: sampleChannel,
    avatarSrc: 'https://placehold.co/72x72/232323/f0f0f0?text=Avatar',
  },
  {
    kind: 'playlist',
    playlist: samplePlaylist,
    thumbnailSrc: 'https://placehold.co/320x180/232323/f0f0f0?text=Playlist',
  },
  { kind: 'hashtag', hashtag: sampleHashtag },
  { kind: 'parse-error', message: null },
]

export const sampleRelatedVideo: RelatedVideo = {
  title: 'A related video about design systems',
  videoId: 'related123',
  author: 'Design Channel',
  authorId: 'UCdesign123',
  authorUrl: '/channel/UCdesign123',
  authorVerified: true,
  videoThumbnails: [
    { quality: 'medium', url: '/vi/related123/mqdefault.jpg', width: 320, height: 180 },
  ],
  lengthSeconds: 845,
  published: now - 12 * DAY,
  publishedText: '12 days ago',
  viewCountText: '892K views',
}

export const sampleComment: ApiComment = {
  author: 'Viewer One',
  authorId: 'UCviewer1',
  authorIsChannelOwner: false,
  authorThumbnail: '/ggpht/viewer1.jpg',
  authorUrl: '/channel/UCviewer1',
  commentId: 'comment123',
  content: 'This interface looks great!',
  contentHtml: '<p>This interface looks great!</p>',
  isEdited: false,
  isPinned: true,
  isSponsor: false,
  likeCount: 482,
  published: now - DAY,
  publishedText: '1 day ago',
  verified: false,
}

export const sampleCommunityPost: CommunityPost = {
  author: 'Invidious',
  authorId: 'UC4QobU6STFB0P71PMvOGN5A',
  authorIsChannelOwner: true,
  authorThumbnails: [{ url: '/ggpht/avatar.jpg', width: 176, height: 176 }],
  authorUrl: '/channel/UC4QobU6STFB0P71PMvOGN5A',
  commentId: 'post123',
  content: 'We shipped the redesign. What do you think?',
  contentHtml: '<p>We shipped the redesign. What do you think?</p>',
  isEdited: false,
  likeCount: 1250,
  published: now - 2 * DAY,
  publishedText: '2 days ago',
  replyCount: 87,
  attachment: null,
}

export const samplePlaylistVideo: PlaylistVideo = {
  author: 'Focus Sounds',
  authorId: 'UCfocus123',
  authorUrl: '/channel/UCfocus123',
  index: 0,
  lengthSeconds: 421,
  liveNow: false,
  title: 'First track in the playlist',
  type: 'video',
  videoId: 'track123',
  videoThumbnails: [
    { quality: 'medium', url: '/vi/track123/mqdefault.jpg', width: 320, height: 180 },
  ],
}
